### ISSUE TITLE
setEasingFunction no longer exists, or how to control easing

### ISSUE THREAD

**Issue by fform** [stefanceriu/SCPageViewController#10]
This looks like you are using `@property (nonatomic, strong) id<SCEasingFunctionProtocol> easingFunction;` which isn't compatible with swift? (It just appears as blank)

Any way this could be exposed to Swift?

**Comment by stefanceriu** [comment]
Hey, I haven't really tested it in swift yet. I'll do it and proper support after I finish what's currently in development.

**Comment by Maleandr** [comment]
You can solve it by importing more headers. This worked for me:
#import <SCPageViewController/SCPageViewController.h>
#import <SCPageViewController/SCCardsPageLayouter.h>
#import <SCScrollView/SCEasingFunction.h>

I guess creating one header file, which will import all headers will be enough for swift compatibility.
