### ISSUE TITLE
touchRefusalArea only blocks for first page

### ISSUE THREAD

**Issue by fform** [stefanceriu/SCPageViewController#11]
If I do this

    [self.pageViewController setTouchRefusalArea:[UIBezierPath bezierPathWithRect:CGRectInset(self.view.bounds, 50, 50)]];

Then it's only refusing touch for that initial bounds. It seems that when you change pages, that refusal area moves with the scrollview.

The only way I've figured to solve this is by moving the refusal area manually after `didNavigateToPageAtIndex`. Is that the correct way to do this or is the lib supposed to keep that refusal area locked to what the user sees? I would expect the later as I'm guessing the whole point of this is to make page swiping only activate towards the edge of the screen.

This is the way I'm moving the refusal area, in the `SCPageViewControllerDelegate`

    func pageViewController(pageViewController: SCPageViewController!, didNavigateToPageAtIndex pageIndex: UInt) {
        var rect = self.view.bounds
        let index = CGFloat(pageIndex)
        rect.origin.x = (rect.width * index) + (pageViewController.layouter.interItemSpacing * index)
        pageViewController.touchRefusalArea = UIBezierPath(rect: CGRectInset(rect, 50, 50))
    }

**Comment by stefanceriu** [comment]
That is indeed the correct way of doing it. The touch refusal area is applied on the scroll view itself so when the offset changes the area should change as well. I guess I could bundle this logic inside the scroll  view but doing so would remove much of the control you have now.

The point of the touch refusal area is not necessarily to enable swiping from the edge of the screen but from anywhere really, any shape any place. Let's say for example you want different touch refusal areas on different pages, moving this logic inside the scroll view would prevent you from doing so.

As an example, in the SCStackViewController demo here https://github.com/stefanceriu/SCStackViewController#side-stacked-with-parallax-and-root-resizing I would use it to allow swiping only from the menu buttons which do change positions when menus are opened.
