### ISSUE TITLE
Half pages?

### ISSUE THREAD

**Issue by fatuhoku** [stefanceriu/SCPageViewController#14]
I have a use-case where I have a sequence of transparent pages that I want to present as horizontal row of pages, except, with the next page overlapping the current page by half a page's width.

I was able to approximate this in the Demo application with the following:

```objc
    SCPageLayouter *layouter = [[SCPageLayouter alloc] init];
    layouter.interItemSpacing = [UIScreen defaultScreen].bounds.size.width / 2;
```

However, I found the snapping behaviour between Page 0 and Page 1 to get confused: the transition stops anywhere, as opposed to snapping to 0% or 50%.

**Comment by stefanceriu** [comment]
I'm not quite sure how this would look but I suggest you have a look at how 'navigation steps' work in the SCStackViewController.
If that's indeed what you need I might be able to port them to the page view controller.

**Comment by fatuhoku** [comment]
Never mind — I went for a different solution in the end!

**Comment by stefanceriu** [comment]
:ok_hand:
