### ISSUE TITLE
Is it possible to insert at current page?

### ISSUE THREAD

**Issue by cerupcat** [stefanceriu/SCPageViewController#18]
I'd like to animate the insertion at the current page. Just how deletion remove the current page and animates the other pages over, I'd like to insert a page at the current index and move apart the current pages. Is that already possible?

**Comment by stefanceriu** [comment]
It wasn't really possible so I added a new layouter method that tells the page view controller to do that.
The default implementation returns true to keep the current behavior so you'll need a custom layouter that returns false.

```objc
- (BOOL)shouldPreserveOffsetForInsertionAtIndex:(NSUInteger)index
                             pageViewController:(SCPageViewController *)pageViewController;
```
