### ISSUE TITLE
Issue in Navigating Back To Home Controller 

### ISSUE THREAD

**Issue by sanjayrathore36** [stefanceriu/SCPageViewController#22]
when adding lots of controller dynamically and moving back to previous controller (i.e. Home Controller) first it shows initial  page of loaded view controllers then goes back.

**Comment by stefanceriu** [comment]
I'm sorry but I don't really understand what that means. Please send me a sample project or snippet that I can use to reproduce the problem.

**Comment by hunaid-hassan-confiz** [comment]
Yes, it does happen when you push the PageViewController and then swipe left i.e. you are at index 1 or above. And then if you push 'back' on the navigation bar; during the pop navigation, the n-1th controller would show up for a split second, given n > 0.

**Comment by MarioBajr** [comment]
Still not clear. Just send a snippet to make it clear.
- Which Layouter are you using?
- Describe the view / view controller hierarchy.
- Any custom easing animation, paging enabled, bounces?

I believe that you just forgot to enable ClipToBounds on the view of the PageViewController.

**Comment by hunaid-hassan-confiz** [comment]
ClipToBounds fixed it. Lotta thanks
Hope it works for the the reporter too.

**Comment by sanjayrathore36** [comment]
By setting this property navigation works smoothly.
thanks Guys

**Comment by stefanceriu** [comment]
:clap: @MarioBajr :smile:
