### ISSUE TITLE
Memory Usage shoots up

### ISSUE THREAD

**Issue by sudeepunnikrishnan** [stefanceriu/SCPageViewController#23]
Hi Stefan

On using SCPageViewController to show about 50 pages ,the memory shoots up to more than 100MB.Tried setting the viewcontrollers to null once shown, but it does not make any changes.

Expecting some solution for this.
Thanks in advance.

**Comment by stefanceriu** [comment]
Hey,

We've been using this in production for a couple of year now and we haven't seen any memory issues.

If you are just working on top of the code from the demo app you should pay attention to the fact that the [dataSource](https://github.com/stefanceriu/SCPageViewController/blob/master/Demo/ObjCDemo/SCRootViewController.m#L29) property acts like a cache but never releases any of the view controllers.

You could listen to the UIApplicationDidReceiveMemoryWarningNotification and replace these view controllers with NSNulls or build the view controllers on the fly and remove the dataSource property all together.

Now, if I'm not right and you indeed found a problem in the component itself please provide me with more details, code or a simple project I can use to reproduce it.

**Comment by sudeepunnikrishnan** [comment]
Hi Stefan

Made changes by building the viecontrollers on the fly,now it seems to be fine.While replacing the view controllers with NSNulls ,it did not make much reduction in memory usage.Well for the time,issue seems to be resolved.

Thanks!

**Comment by stefanceriu** [comment]
:+1:
