### ISSUE TITLE
how to set custom page title for views? [SCSafariPageController]

### ISSUE THREAD

**Issue by whisper-bye** [stefanceriu/SCPageViewController#24]
the project SCSafariPageController does not seem issues window, so I post my questions at here

I want to set page title likes in safari, thx! @stefanceriu 

![](http://media.idownloadblog.com/wp-content/uploads/2014/01/How-to-close-all-Safari-tabs-screenshot-001.png)

**Comment by stefanceriu** [comment]
I'm going to assume you are working on top of the demo project in which case creating that title is as simple as adding a new UILabel to the SCViewController.xib file (ViewController.xib for the swift demo) next to the close button.

Now, considering this is a pretty basic question and has nothing to do with the SafariPageController component itself, it might be better to start from somewhere like StackOverflow next time.

Cheers,
Stefan
