### ISSUE TITLE
Vertical Scrolling the Pages

### ISSUE THREAD

**Issue by sanjayrathore36** [stefanceriu/SCPageViewController#29]
Hi,
 set pagingEnabled=true and continuousNavigationEnabled=true. Now  When you scroll vertically then some time it scrolls multiple pages at once  not single page.

**Comment by stefanceriu** [comment]
Hey, I'm sorry but that's expected behaviour. The page view controller will block navigation by more then one page only when continuous navigation is disabled. Otherwise, if the paging is enabled, it will try to center on the page that's closest to the target content offset.

**Comment by sanjayrathore36** [comment]
Thanks for you reply. But when i set continuousNavigationEnabled=false and using vertical sliding .
when you try to swap/slide pages fastly it does not work very well.  Pages does not changes.
I have also set self.scrollView.decelerationRate = UIScrollViewDecelerationRateFast; but does not work very well.

**Comment by sanjayrathore36** [comment]
One more thing . if you will create lots of dynamic pages and do vertical scrolling . Swapping fastly does not changes pages

**Comment by stefanceriu** [comment]
Well you can't really have it both ways. I am using negative content insets to block navigation to just one page at a time (continuousNavigationEnabled=false) and then update them every time the scroll view rests. This, of course, will block you from swiping through pages fast.
