### ISSUE TITLE
Smooth Vertical scrolling with lots of dynamic pages issue 

### ISSUE THREAD

**Issue by sanjayrathore36** [stefanceriu/SCPageViewController#30]
If there are lots of pages and when you try to swap/slide pages fastly it does not work very well. Pages does not changes.
I have also set self.scrollView.decelerationRate = UIScrollViewDecelerationRateFast; but does not work very well.

**Comment by stefanceriu** [comment]
I'm not entirely sure what's going wrong in your case but I have never had problems with large number of pages.
Maybe you can post some sample code so I can see what's going on.

On the other hand, the pageViewController's scrollView defaults to UIScrollViewDecelerationRateFast so I'm not sure why you are setting it https://github.com/stefanceriu/SCPageViewController/blob/master/SCPageViewController/SCPageViewController.m#L104

**Comment by sanjayrathore36** [comment]
I have also run your example it has same issue . Steps to reproduce 

1. Create Vertical scrolling 
2- Crate almost 70 pages 
3- Now use page sliding option 
4- if you change pages slowly it  works well.
5- Now try to changes pages quickly .It does not work very well

**Comment by stefanceriu** [comment]
Try enabling both continuousNavigation and paging and see if that fixes the problem.

```
[self.pageViewController setContinuousNavigationEnabled:YES];
[self.pageViewController setPagingEnabled:YES];
```
