### ISSUE TITLE
How do I make a pageControl to navigate with the page correctly?

### ISSUE THREAD

**Issue by allenlinli** [stefanceriu/SCPageViewController#31]
I tried to put on a pageControl, but I can not navigate the pageControl correctly.

I used to use those SCPageViewControllerDelegate, but they don't work quite well.
Sometimes it's because of the bounce, if I can turn the bounce off, I could probably work it out.

The following code a problem: When I slide to another page but it bounce back, the pageControl will be incorrect.

```
func pageViewController(pageViewController: SCPageViewController!, didHideViewController controller: UIViewController!, atIndex index: UInt)
    {
        pageControl.currentPage = Int(willShowPageIndex!)
    }
    
    func pageViewController(pageViewController: SCPageViewController!, didShowViewController controller: UIViewController!, atIndex index: UInt)
    {
        willShowPageIndex = index
    }
```

Cheers,

**Comment by allenlinli** [comment]
I solved it with this algorithm:

```
func pageViewController(pageViewController: SCPageViewController!, didHideViewController controller: UIViewController!, atIndex index: UInt)
    {
        if index != willShowPageIndex
        {
            pageControl.currentPage = Int(willShowPageIndex!)
        }
    }
    
    func pageViewController(pageViewController: SCPageViewController!, didShowViewController controller: UIViewController!, atIndex index: UInt)
    {
        willShowPageIndex = index
    }
```

**Comment by stefanceriu** [comment]
Hey, I'm not entirely sure but the simplest way to listen to page index change events is to implement the `didNavigateToPageAtIndex` delegate method
``` func pageViewController(pageViewController: SCPageViewController!, didNavigateToPageAtIndex pageIndex: UInt)``` and use that pageIndex to update your pageControl.

Optionally, if you also want to make the pageControl move the pageViewController's current page you can use the following method
```navigateToPageAtIndex(pageIndex: UInt, animated: Bool, completion: (() -> Void)!)```

**Comment by allenlinli** [comment]
Thank you for providing answers. 

I tried to do the same thing like `func pageViewController(pageViewController: SCPageViewController!, didNavigateToPageAtIndex pageIndex: UInt)`. The problem of that function is the pageControl change a little bit late, which is about 0.4s lag.

Compare to UIPageController. If I use UIPageController, then I can change pageControl.currentPage at the following code, which will change the pageControl.currentPage at perfect timing.

```
-(void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView {
    self.page.currentPage = [self horizontalPageNumber:scrollView];
}

- (void)scrollViewDidEndDragging:(UIScrollView *)scrollView willDecelerate:(BOOL)decelerate {
    if (!decelerate) self.page.currentPage = [self horizontalPageNumber:scrollView];
}
```

**Comment by stefanceriu** [comment]
As luck would have it, `didNavigateToPageAtIndex` is called from the same two methods you posted [scrollViewDidEndDecelerating](https://github.com/stefanceriu/SCPageViewController/blob/master/SCPageViewController/SCPageViewController.m#L672) and [scrollViewDidEndDragging](https://github.com/stefanceriu/SCPageViewController/blob/master/SCPageViewController/SCPageViewController.m#L658) inside the pageViewController's implementation.

Anyway, the easiest way update you page control as soon as possible is to listen to the 
`- (void)pageViewController:(SCPageViewController *)pageViewController didNavigateToOffset:(CGPoint)offset`
delegate call and keep updating your page number through the `pageViewController.currentPageProperty`

**Comment by allenlinli** [comment]
I understood. Cheers.
