### ISSUE TITLE
Passing through gestures

### ISSUE THREAD

**Issue by H2OBorne** [stefanceriu/SCPageViewController#32]
Is there a recommended way to pass gestures through to an UIScrollView embedded within one of the UIViewControllers presented by the SCPageViewController? I would ideally like to handle `viewDidScrollView:` for the presented UIScrollView in one of the presented UIViewControllers.

I note that UICollectionViews function just fine.

I'm assuming I've totally overlooked something.

Thanks!

**Comment by stefanceriu** [comment]
Hey, as far as I know there's nothing special you need to do. I managed to pass touches to an embedded scroll view just by adding it to the hierarchy and settings it's content size to something reasonable. 
Here's how it looks:
![embeddedscrollview](https://cloud.githubusercontent.com/assets/637564/17128305/5c25235c-5314-11e6-8a56-d8dbd7d4fac2.gif)

**Comment by H2OBorne** [comment]
Oh sweet. I'll check again. I was having trouble with an UIScrollView filling the entire page, but this is the same concept. Surely something dumb has happened.

Thanks :)

**Comment by stefanceriu** [comment]
No problem, let me know how it goes.
