### ISSUE TITLE
pod try broken?

### ISSUE THREAD

**Issue by davidseek** [stefanceriu/SCPageViewController#33]
<img width="500" alt="bildschirmfoto 2016-09-17 um 09 27 47" src="https://cloud.githubusercontent.com/assets/17073950/18606759/16f23cb0-7cb9-11e6-8629-4e64a60bfbb1.png">

**Comment by stefanceriu** [comment]
Hey, sorry about the late reply, I finally got around to updating the demo projects so it should be okay now.
