### ISSUE TITLE
Any possible way to remove deceleration delay when paging?

### ISSUE THREAD

**Issue by joenot443** [stefanceriu/SCPageViewController#35]
Essentially, I've noticed that when navigating through pages, it takes about 0.3s for the page to 'settle' and reach its final destination. It eases the edge of the page into place slightly slower than I'd like, I'd like to reduce or remove this delay if possible.

I can attach a GIF of what I mean if needed, hopefully I've explained myself correctly though.

Thanks!

**Comment by stefanceriu** [comment]
Hi Joe,

Unfortunately, as the component is based on an UIScrollView, the deceleration rate is restricted to `UIScrollViewDecelerationRateNormal` or `UIScrollViewDecelerationRateFast` and it's already set to use fast by default.

The only workaround I can think of is to observe scroll events and manually change the content offset once a threshold has been reached.
