### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by akotulu** [stefanceriu/SCPageViewController#38]
Hei!

Really nice work, I searched for a library that has insert and delete view controllers built in, but found none and I searched for days. Then I found yours, works like a charm and has every needed delegate included with some sugar. I mean if you want more stars make a swift version. You'd be only one to support this mandatory feature that everyone else seems to forget. All other libraries take a static array and only support reloadAll which isn't smooth transition. 

Would be nice if you included infinite paging, last page returns to first.

Btw example project didn't compile :)

👍

**Comment by stefanceriu** [comment]
Hey, thank you, I'm happy you find it useful.
I have no intention of porting it to swift or adding any more features, at least for now, but I will happily accept reasonable pull request.

I am curios why the demo project isn't building for you though, they both seem to be fine on my side. It would be great if you could give me some more details on that.

**Comment by akotulu** [comment]
Ok, tested it with pod try and everything works fine. Im used to just download the project as a zip and this way it wont compile :)

**Comment by akotulu** [comment]
Well I found a issue which I tried to fix but failed. My view controllers are set up using AutoLayout and when I insert a new controller to the pageViewController using method 
`open func insertPages(at indexes: IndexSet!, animated: Bool, completion: (() -> Swift.Void)!)`
view isn't displayed properly. 

Here are the screenshots.
[Wrong - button and top are off](http://existanz.planet.ee/temp/wrong.PNG)
[Correct - stretched properly](http://existanz.planet.ee/temp/correct.PNG)

Current solution I found is to add the view to the hierarchy and then remove it before calling insert function like so
```
self.containerView.insertSubview(viewController.view, at: 0)
viewController.view.removeFromSuperview()

self.viewControllers.insert(viewController, at: 0)
self.pageViewController.insertPages(at: IndexSet(integer: 0), animated: false, completion: nil)
```

This way the view is displayed correctly.

**Comment by stefanceriu** [comment]
I'm thinking it might be caused by certain constraints being broken when first inserting the page because of zero frames. Can you please send me a small demo project where this happens so I have something to debug on top of ?

**Comment by akotulu** [comment]
Hey!

Put together a small project from my current one. Press the add button twice to see the second view controller is smaller and bottom toolbar isn't where it should.

[Project](http://existanz.planet.ee/temp/PageController.zip)

**Comment by stefanceriu** [comment]
Hey, sorry for the late reply.
That link you posted seems to be broken now, have you been able to figure out the issue in the mean time ?

**Comment by akotulu** [comment]
Hey, link works for me.

**Comment by stefanceriu** [comment]
I'm not entirely following your theory as I don't understand why appearance transition calls would affect view controller frames. Debugging your project also seems to reveal that both view controllers have equal sizes 

```(lldb) po self.viewControllers
▿ 2 elements
  ▿ 0 : <PageController.LumenViewController: 0x7fcba450dab0>
  ▿ 1 : <PageController.AlcoViewController: 0x7fcba450b3a0>


(lldb) po self.viewControllers.first?.view.frame
▿ Optional<CGRect>
  ▿ some : (0.0, 0.0, 1024.0, 704.0)
    ▿ origin : (0.0, 0.0)
      - x : 0.0
      - y : 0.0
    ▿ size : (1024.0, 704.0)
      - width : 1024.0
      - height : 704.0
(lldb) po self.viewControllers.last?.view.frame
▿ Optional<CGRect>
  ▿ some : (1074.0, 0.0, 1024.0, 704.0)
    ▿ origin : (1074.0, 0.0)
      - x : 1074.0
      - y : 0.0
    ▿ size : (1024.0, 704.0)
      - width : 1024.0
      - height : 704.0
```

What I also did is to trim down your view controller to their most basic form and found that their frames are yet again correct. You can find my modifications on your sample project [here](https://github.com/stefanceriu/SCPageViewController/files/1212607/PageController.zip)

All of these lead me to believe there's something wrong within your project and not the pageViewController. 


As for the other thing you mentioned ...
>Also currently there is no way to use UIPageControl, cause of missing delegate willShowViewController. Currently available didShowViewController report too late and animation looks out of sync - page animation ends and dot starts to animate.

I would suggest you hook your UIPageControl to one the following pageViewController delegate  methods

```
- (void)pageViewController:(SCPageViewController *)pageViewController
	   didNavigateToOffset:(CGPoint)offset;

- (void)pageViewController:(SCPageViewController *)pageViewController
  didNavigateToPageAtIndex:(NSUInteger)pageIndex;
```

and the ```@property (nonatomic, readonly) NSUInteger currentPage;``` property

**Comment by akotulu** [comment]
If you run my initial project in simulator or device of your choosing and press add button on top, then scroll to the new view controller. Look at the element positions, they are not placed correctly. The view size is same I know, problem is where the elements are. I'm guessing calling these methods inside animation will interrupt constraint calculation. As docs indicate, constraint calculation is long multipart process.

**Comment by stefanceriu** [comment]
Right, so as far as I can tell all your problems are caused by constraints setup to follow layout margins, quite a few of them actually.
I've put together [this video](https://drive.google.com/open?id=0ByLCkUO90ltoOGliclBrcHRhUWc) that will show you how to modify them and get everything working properly.

![screen shot 2017-08-14 at 08 38 30](https://user-images.githubusercontent.com/637564/29260447-93c17e5e-80d2-11e7-9ef2-a8197b8b887c.png)

**Comment by akotulu** [comment]
Nice one, good find 👍 
Seems I was wrong all along, thank you for sorting this issue out, had problems with this before. 
Well if you can, maybe update docs, someone else could have this problem.
