### ISSUE TITLE
setBouces: described in documentation is missing

### ISSUE THREAD

**Issue by ekazaev** [stefanceriu/SCPageViewController#39]
Actually it was the only reason why i tried this control.
layouter.navigationConstraintType = SCPageLayouterNavigationContraintTypeNone did not fix bouncing effect either

Also if Iphone orientation changes swipes back to the previous page automaticaly

**Comment by stefanceriu** [comment]
I've exposed full access to the internal scrollView a while back so you can just
```[self.pageViewController.scrollView setBounces:NO];```

As for the other issue, the demo projects don't seem to have this problem so you're going to have to send me a sample project where it happens.
