### ISSUE TITLE
I want SCSlidingPageLayouter to roll forward and roll backwards. In the same way。

### ISSUE THREAD

**Issue by xiushaomin** [stefanceriu/SCPageViewController#41]
what can I do?

**Comment by stefanceriu** [comment]
Hey, I'm not entirely sure what that means but generally pageLayouters are there to allow you to customize transitions. I suggest you write your own based on the `SCPageLayouterProtocol` and make it work however you see fit.

**Comment by xiushaomin** [comment]
ok，Thank you very much.
