### ISSUE TITLE
App Crashes Due to 'CALayer position contains NaN: [nan nan]' When Applying Other transformations.

### ISSUE THREAD

**Issue by williamfs** [stefanceriu/SCPageViewController#43]
I'm using this library in conjunction with [GSKStrechyHeaderView](https://github.com/gskbyte/GSKStretchyHeaderView) in attempts to recreate a UI similar to Pinterest . A detail view expands from a user selecting a CollectionViewCell. Users can swipe through multiple detail views using this wonderful library. Then can dismiss the view and it'll scale back back down to the corresponding CollectionViewCell.

The issue I'm running into is when adding the following lines in the delegate method of the strechy header view (which tells me the percentage it has stretched):

        CGAffineTransform scale = CGAffineTransformMakeScale(currentScale, currentScale);
        CGAffineTransform translate = CGAffineTransformMakeTranslation(currentX, currentY);
        view.transform = CGAffineTransformConcat(translate, scale);

When I select the first row in the CollectionView on the initial view controller, which presents the SCPageViewController I get the following error, along with an exception error on line 621 of SCPageController.m

Line 621: `[viewController.view setFrame:nextFrame];`

` *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'`

When disabling my transformations, it works flawlessly, but with it, I run into issues. Any assistance or guidance would be greatly appreciated.

**Comment by stefanceriu** [comment]
Hey, it's been a long time since I had to deal with this in the pageViewController but if I'm not mistaken setting frames doesn't work properly when used together with `UIView` affine transformations. The documentation states that ```Warning 
When the value of this property is anything other than the identity transform, the value in the frame property is undefined and should be ignored.```

Now, the pageViewController uses frame setting and supports transformations so the way I got them to work together is to set CATransform3Ds on the sublayers through something like the following. It's not ideal, but hey, it's better than nothing.
```objc
- (void)_setAnimatableSublayerTransform:(CATransform3D)transform forViewController:(UIViewController *)viewController
{
    for(CALayer *layer in viewController.view.layer.sublayers) {
        [layer setTransform:transform];
    }
}
```

**Comment by williamfs** [comment]
Cool! Thank you for the info. Sorry I missed that in the docs!

**Comment by stefanceriu** [comment]
My pleasure, hope it helps !
