### ISSUE TITLE
Issue with Continuous Navigation Enabled

### ISSUE THREAD

**Issue by kamilemed** [stefanceriu/SCPageViewController#44]
Hello,

I have noticed that when continuousNavigationEnabled is set to YES and removal of pages is implemented with data reload, bounds are not updated and empty last page remains. 

The possible solution I came up with is taking [self _updateBoundsAndConstraints] outside of the "else" block in SCPageViewController's reloadData method.

Please find my example project here: https://github.com/kamilemed/SCPageControlerExample

**Comment by stefanceriu** [comment]
Hi there, really good catch! I think you're right about the solution but I would go one step further and move `tilePages` outside too, getting rid of the else entirely.

If you don't see a problem with that I'll make the changes and release a new version, let me know.

Cheers,
Stefan

**Comment by kamilemed** [comment]
Thanks for a quick response. No, no problem with that from my point of view. Looking forward to the new release.

**Comment by stefanceriu** [comment]
Okay, fix pushed and version released 🎉 
Thank you for taking the time to raise the issue and help me out with a proper example.

Cheers!
