### ISSUE TITLE
viewWillAppear & viewDidAppear events are not getting propagated to the active page's viewcontroller

### ISSUE THREAD

**Issue by itchingpixels** [stefanceriu/SCPageViewController#7]
This is useful if someone is presenting a modal on a pageviewcontroller, and if that's dismissed, the original ViewController's viewWillAppear and viewDidAppear function should be called.

At least that's the expected behavor, SCPageViewController currently not forwarding these events.

**Comment by itchingpixels** [comment]
I may be mistaken, and it's possible to UIPageViewController won't forward these events.

Anyway, I'm gonna create a pull request for this now:)

**Comment by stefanceriu** [comment]
The tilePages method (called from viewWillAppear and viewDidDisappear) should call the updateFramesAndTriggerAppearanceCallbacks method and correctly forward the events to the child view controllers. Either way, I'm going to have a look at it asap and fix it if needed.

**Comment by itchingpixels** [comment]
thank you, I'll try to reproduce it in a standalone project and send it to you later today!

**Comment by stefanceriu** [comment]
I did a couple of tests just now and everything seems to be working as intended, did you manage to reproduce anything on your side ?
