### ISSUE TITLE
View controller is removed on `viewDidDisappear:`

### ISSUE THREAD

**Issue by markst** [stefanceriu/SCPageViewController#9]
I push a new VC to my navigation stack, which causes my `SCPageViewController` to trigger `viewDidDisappear` & `tilePages` my child view controller is removed due to `isViewVisible` property. The view controller is then added again upon returning.

**Comment by markst** [comment]
Not sure why `tilePages` needs to be called on `viewDidDisappear:`

**Comment by stefanceriu** [comment]
The reason is that I want viewWillDisappear and viewDidDisappear to be called on all the previously visible child view controllers, which I believe to be expected behavior. As for them getting removed from the superview, I'm not sure why that would be a bad thing. How does it affect you ?
